// source/core/encrypt_decrypt.h
// Implementation of Encrypt/Decrypt for Apex Obfuscator
// https://github.com/is-nobody/apex-obfuscator
// MIT license

#ifndef ENCRYPT_DECRYPT_H
#define ENCRYPT_DECRYPT_H

#include <stdint.h>
#include "sbox.h"
#include "keygen.h"

// encrypts one 16-byte block in-place using the expanded round keys.
// round_keys must contain ROUNDS+1 (15) keys of 16 bytes each,
// generated by keygen_expand from the master key.
// the block is transformed through 14 rounds plus initial whitening.
void encrypt_block(uint8_t *block, uint8_t round_keys[ROUNDS + 1][BLOCK_SIZE]);

// decrypts one 16-byte block in-place using the expanded round keys.
// applies the inverse aes operations in reverse order.
// the same round_keys array from encryption is used (not a separate decryption schedule).
void decrypt_block(uint8_t *block, uint8_t round_keys[ROUNDS + 1][BLOCK_SIZE]);

#endif